### ISSUE TITLE
Invalid withlandscape

### ISSUE THREAD

**Issue by dotqi** [chromedp/cdproto#8] opened 2020-05-15 01:45 UTC
When generating PDF using chromedp.

It takes effect when using withlandscape to generate horizontal PDF. The generated PDF is still vertical.

code:

err := chromedp.Run(ctx, chromedp.Tasks{

chromedp.Navigate(url),

chromedp.WaitReady("body"),

chromedp.ActionFunc(func(ctx context.Context) error {

var err error

p := page.PrintToPDF().WithLandscape(true)

buf, _, err = p.Do(ctx)

return err

}

}

**Comment by mvdan** [comment] 2020-06-08 13:24
Duplicate of https://github.com/chromedp/chromedp/issues/625. Please don't file issues twice.

**Closed by mvdan** 2020-06-08 13:24 UTC
